# Generated by Django 3.0.5 on 2020-05-11 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('speels', '0002_auto_20200505_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='genre',
            field=models.ManyToManyField(blank=True, help_text='Select a genre for this game.', to='speels.Genre'),
        ),
        migrations.AlterField(
            model_name='section',
            name='type',
            field=models.CharField(choices=[('q', 'Question-Answer'), ('l', 'Labyrint'), ('s', 'Shape')], default='q', help_text='Game type', max_length=1),
        ),
        migrations.CreateModel(
            name='Pin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('restart', models.IntegerField(default=0)),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='speels.Game')),
            ],
        ),
    ]
